### ISSUE TITLE
基于xml托管时 spring bean property为bean 时 无法自动reload问题

### ISSUE THREAD

**Issue by youfengfeng** [knightliao/disconf#101]
直接看示例：
`    <bean id="springLoad" class="com.yaxon.log.clean.SpringLoad">
        <property name="loadInner">
            <bean class="com.yaxon.log.clean.LoadInner">
                <property name="retainDay" value="${retain.day}"/>
                <property name="targetDirectory" value="${target.directory}"/>
                <property name="executeTime" value="${execute.time}"/>
            </bean>
        </property>
    </bean>`
以上首次加载正常，配置文件中的retain.day、target.directory、execute.time发生变化的时候无法自动对LoadInner进行reload。报错如下（似乎是直接将retainDay、targetDirectory、executeTime当成是SpringLoad类的熟悉进行reload而产生的错）：
`org.springframework.beans.NotWritablePropertyException: Invalid property 'remainDay' of bean class [com.yaxon.log.clean.SpringLoad]: Bean property 'remainDay' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at org.springframework.beans.BeanWrapperImpl.setPropertyValue(BeanWrapperImpl.java:1064)
	at org.springframework.beans.BeanWrapperImpl.setPropertyValue(BeanWrapperImpl.java:902)
	at com.baidu.disconf.client.addons.properties.ReloadingPropertyPlaceholderConfigurer.propertiesReloaded(ReloadingPropertyPlaceholderConfigurer.java:231)
	at com.baidu.disconf.client.addons.properties.ReloadablePropertiesBase.notifyPropertiesChanged(ReloadablePropertiesBase.java:62)
	at com.baidu.disconf.client.addons.properties.ReloadablePropertiesBase.setProperties(ReloadablePropertiesBase.java:76)
	at com.baidu.disconf.client.addons.properties.ReloadablePropertiesFactoryBean.doReload(ReloadablePropertiesFactoryBean.java:228)
`

目前采取的解决办法如下：

`    <bean id="appconfig" class="com.yaxon.log.clean.AppConfig">
        <property name="retainDay" value="${retain.day}"/>
        <property name="targetDirectory" value="${target.directory}"/>
        <property name="executeTime" value="${execute.time}"/>
    </bean>

        <bean id="loadInner" class="com.yaxon.log.clean.LoadInner">
        <property name="remainDay" value="${retain.day}"/>
        <property name="targetDirectory" value="${target.directory}"/>
        <property name="executeTime" value="${execute.time}"/>
    </bean>

    <bean id="springLoad" class="com.yaxon.log.clean.SpringLoad">
        <property name="loadInner">
            <ref bean="loadInner"/>
        </property>
    </bean>`

即可实现成功reload。
是否基于xml托管时 spring bean property为bean的属性只能为普通的属性，无法支持bean、map类的属性

**Comment by knightliao** [comment]
感谢提供建议，先使用临时方案，我后面会尽量支持

**Comment by youfengfeng** [comment]
建议可以支持在如下的LoadInner配置信息改变后，可触发到SpringLoad类中的setLoadInner方法，从而方便支持SpringLoad的自动重新加载，减少为了自动加载添加的不必要的繁琐代码。
<bean id="springLoad" class="com.yaxon.log.clean.SpringLoad">
        <property name="loadInner">
            <bean class="com.yaxon.log.clean.LoadInner">
                <property name="retainDay" value="${retain.day}"/>
                <property name="targetDirectory" value="${target.directory}"/>
                <property name="executeTime" value="${execute.time}"/>
            </bean>
        </property>
    </bean>

**Comment by mqian-sky** [comment]
<bean id="loadInner" class="com.yaxon.log.clean.LoadInner">
        <property name="remainDay" value="${retain.day}"/>
        <property name="targetDirectory" value="${target.directory}"/>
        <property name="executeTime" value="${execute.time}"/>
    </bean>

请问：在xml 配置里面配置一个bean    ${retain.day} 是对应.properties文件的值 ，在disconf-web修改retain.day的值 对应  loadInner bean  remainDay的值会跟着修改？

我现在的问题是 web修改了  我loadInner bean  remainDay 的值没有修改。

不知道问题出在哪里。请帮我看下:

disconf 配置 
`<context:component-scan base-package="com.baidu" />
	<aop:aspectj-autoproxy proxy-target-class="true" />
	<context:annotation-config />

	<bean id="disconfMgrBean" class="com.baidu.disconf.client.DisconfMgrBean"
		destroy-method="destroy">
		<property name="scanPackage" value="com.baidu.disconf" />
	</bean>

	<bean id="disconfMgrBean2" class="com.baidu.disconf.client.DisconfMgrBeanSecond"
		init-method="init" destroy-method="destroy">
	</bean>

	
	<bean id="configproperties_disconf"
		class="com.baidu.disconf.client.addons.properties.ReloadablePropertiesFactoryBean">
		<property name="locations">
			<list>
				<value>classpath:test.properties</value>
			</list>
		</property>
	</bean>

	<bean id="propertyConfigurer_disconf"
		class="com.baidu.disconf.client.addons.properties.ReloadingPropertyPlaceholderConfigurer">
		<property name="ignoreResourceNotFound" value="true" />
		<property name="ignoreUnresolvablePlaceholders" value="true" />
		<property name="propertiesArray">
			<list>
				<ref bean="configproperties_disconf" />
			</list>
		</property>
	</bean>

	
	<bean id="configproperties_no_reloadable_disconf"
		class="com.baidu.disconf.client.addons.properties.ReloadablePropertiesFactoryBean">
		<property name="locations">
			<list>
				<value>classpath:jdbc.properties</value>
			</list>
		</property>
	</bean>

	<bean id="propertyConfigurerForProject1"
		class="org.springframework.beans.factory.config.PropertyPlaceholderConfigurer">
		<property name="ignoreResourceNotFound" value="true" />
		<property name="ignoreUnresolvablePlaceholders" value="true" />
		<property name="propertiesArray">
			<list>
				<ref bean="configproperties_no_reloadable_disconf" />
			</list>
		</property>
	</bean>
	
	<bean id="testConfig"
          class="com.axatp.amc.model.TestConfig">
        <property name="hosts" value="${hosts}"/>
    </bean>`

test.properties 的配置
hosts=10.100.12.145

访问配置的代码

@Controller
public class IndexController {
  @Inject
  private TestConfig testConfig;
  @RequestMapping("/index")
  public String index() {
      System.out.println(testConfig.getHosts());  @1
      return "index";
  }
}

@1  client 第一次启动后访问 的值：10.100.12.145 
web修改后的值也是:10.100.12.145

没有修改过。
