### ISSUE TITLE
删掉本地配置的properties文件夹，发现报错找不到配置

### ISSUE THREAD

**Issue by zszheng** [knightliao/disconf#102]
Caused by: java.lang.NumberFormatException: For input string: "${storeDataTask.multiThread.threadMax}"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:569)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.springframework.util.NumberUtils.parseNumber(NumberUtils.java:155)
	at org.springframework.beans.propertyeditors.CustomNumberEditor.setAsText(CustomNumberEditor.java:115)
	at org.springframework.beans.TypeConverterDelegate.doConvertTextValue(TypeConverterDelegate.java:455)
	at org.springframework.beans.TypeConverterDelegate.doConvertValue(TypeConverterDelegate.java:427)
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:181)
	at org.springframework.beans.BeanWrapperImpl.convertIfNecessary(BeanWrapperImpl.java:448)
	... 70 more

    
    <bean id="storeDataTaskExecService" class="com.bilibili.message.service.impl.StoreDataTaskExecServiceImpl">
        <property name="threadMax" value="${storeDataTask.multiThread.threadMax}"/>
    </bean>

**Comment by knightliao** [comment]
是不是 disconf.enable.remote.conf=true 这个没有设置？

**Comment by knightliao** [comment]
应该是没有设置成功
