### ISSUE TITLE
DisconfDataGetter.getByFile("redis.properties")会不会存在线程安全问题？

### ISSUE THREAD

**Issue by fiyang** [knightliao/disconf#157]
当我调用   DisconfDataGetter.getByFile("redis.properties");
这样的方法查看内存堆栈，发现用的是hashmap,这个hashmap 回不会有线程安全问题。
会不会  有watcher修改其中的某个值？

"main" prio=5 tid=0x00007fe0b300a800 nid=0x1703 runnable [0x0000700000219000]
   java.lang.Thread.State: RUNNABLE
	at java.util.HashMap.inflateTable(HashMap.java:317)
	at java.util.HashMap.put(HashMap.java:488)
	at com.baidu.disconf.client.common.model.DisconfCenterFile.getKV(DisconfCenterFile.java:134)
	at com.baidu.disconf.client.usertools.impl.DisconfDataGetterDefaultImpl.getByFile(DisconfDataGetterDefaultImpl.java:28)
	at com.baidu.disconf.client.usertools.DisconfDataGetter.getByFile(DisconfDataGetter.java:22)
	at com.example.disconf.demo.task.DisconfDemoTask.run(DisconfDemoTask.java:62)
	at com.example.disconf.demo.DisconfDemoMain.main(DisconfDemoMain.java:36)

**Comment by knightliao** [comment]
1. 有可能会有读写瞬间不一致问题。也就是 我在读时，刚好有配置被更改了。这时读出来的数据可能会脏。（概率会比较低，这个我会着手解决）建议目前可以在访问量少时进行。
2. hashmap如果多线程不停的append数据在rehash时是会出现程序异常的。但disconf在程序启动后，hashmap的大小就已经定好了。不会出现多线程append引起的rehash问题。
