### ISSUE TITLE
除zookeeper放在linux系统中，其他都是window系统测试出现java.nio.file.InvalidPathException

### ISSUE THREAD

**Issue by lyg123** [knightliao/disconf#166]

**Comment by lyg123** [comment]
remote.properties : /F:/GitHub/disconf-demos-java.git/disconf-standalone-demo/target/classes/\remote.properties
2016-09-07 17:58:50,768 [main-EventThread] ERROR com.baidu.disconf.client.core.processor.impl.DisconfFileCoreProcessorImpl - java.nio.file.InvalidPathException: Illegal char <:> at index 2: /F:/GitHub/disconf-demos-java.git/disconf-standalone-demo/target/classes/\remote.properties
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /F:/GitHub/disconf-demos-java.git/disconf-standalone-demo/target/classes/\remote.properties
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[na:1.8.0_102]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[na:1.8.0_102]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[na:1.8.0_102]
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94) ~[na:1.8.0_102]
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255) ~[na:1.8.0_102]
	at java.nio.file.Paths.get(Paths.java:84) ~[na:1.8.0_102]
	at com.example.disconf.demo.service.callbacks.UpdatePipelineCallback.readFile(UpdatePipelineCallback.java:20) ~[classes/:na]
	at com.example.disconf.demo.service.callbacks.UpdatePipelineCallback.reloadDisconfFile(UpdatePipelineCallback.java:28) ~[classes/:na]
	at com.baidu.disconf.client.core.processor.impl.DisconfFileCoreProcessorImpl.callUpdatePipeline(DisconfFileCoreProcessorImpl.java:182) [disconf-client-2.6.35.jar:na]
	at com.baidu.disconf.client.core.processor.impl.DisconfFileCoreProcessorImpl.updateOneConfAndCallback(DisconfFileCoreProcessorImpl.java:166) [disconf-client-2.6.35.jar:na]
	at com.baidu.disconf.client.watch.inner.DisconfSysUpdateCallback.reload(DisconfSysUpdateCallback.java:24) [disconf-client-2.6.35.jar:na]
	at com.baidu.disconf.client.watch.inner.NodeWatcher.callback(NodeWatcher.java:145) [disconf-client-2.6.35.jar:na]
	at com.baidu.disconf.client.watch.inner.NodeWatcher.process(NodeWatcher.java:90) [disconf-client-2.6.35.jar:na]
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:526) [zookeeper-3.3.6.jar:3.3.6-1366786]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:502) [zookeeper-3.3.6.jar:3.3.6-1366786]

**Comment by lyg123** [comment]
window下java.nio.Paths.getPath()支持这种格式的F:/GitHub/disconf-demos-java.git/disconf-standalone-demo/target/classes/remote.properties
估计要修改String com.baidu.disconf.client.common.model.DisconfCenterFile.getFilePath()
或者 String com.baidu.disconf.core.common.utils.OsUtil.pathJoin(String... pathElements)，统一解决这个路径问题

**Comment by knightliao** [comment]
感谢报错，我会尽快修复

**Comment by xiangzhiwei** [comment]
这个应该是跑disconf-statndalong-demo出来的吧

**Comment by knightliao** [comment]
fix http://disconf.readthedocs.io/zh_CN/latest/others/src/update.html
