### ISSUE TITLE
reflections 版本冲突

### ISSUE THREAD

**Issue by nnnggel** [knightliao/disconf#199]
maven 编译的时候，发现当前项目使用的 reflections 版本和 disconf 中所使用的冲突（0.9.10 / 0.9.9-RC1），请问是否有解决方法？
详细信息如下：
java.lang.NoSuchMethodError: org.reflections.util.FilterBuilder.includePackage(Ljava/lang/String;)Lorg/reflections/util/FilterBuilder;
    at com.baidu.disconf.client.scan.inner.statically.strategy.impl.ReflectionScanStatic.getReflection(ReflectionScanStatic.java:72)
    at com.baidu.disconf.client.scan.inner.statically.strategy.impl.ReflectionScanStatic.scanBasicInfo(ReflectionScanStatic.java:184)
    at com.baidu.disconf.client.scan.inner.statically.strategy.impl.ReflectionScanStatic.scan(ReflectionScanStatic.java:56)
    at com.baidu.disconf.client.scan.impl.ScanMgrImpl.firstScan(ScanMgrImpl.java:68)
    at com.baidu.disconf.client.DisconfMgr.firstScan(DisconfMgr.java:94)
    at com.baidu.disconf.client.DisconfMgrBean.postProcessBeanDefinitionRegistry(DisconfMgrBean.java:75)
    at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273)
    at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:111)
    at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:678)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:520)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
    at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
    at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
    at com.omniprimeinc.framework.server.ApplicationStarter.run(ApplicationStarter.java:35)
    at com.omniprimeinc.framework.server.example.server.Application.main(Application.java:8)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

**Comment by knightliao** [comment]
这个后续我有计划升级为最新的版本，
现在为了兼容性，建议 你可以先将你的版本降下来，先和我一样

**Comment by nnnggel** [comment]
thx
