### ISSUE TITLE
应用启动后web平台实例消失

### ISSUE THREAD

**Issue by ewnit** [knightliao/disconf#203]
#200 这个issue没有给出解决方案

服务端报错信息如下：

```
disconf_1  | com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 22
disconf_1  | 	at com.google.gson.Gson.fromJson(Gson.java:815) ~[gson-2.2.4.jar:na]
disconf_1  | 	at com.google.gson.Gson.fromJson(Gson.java:768) ~[gson-2.2.4.jar:na]
disconf_1  | 	at com.google.gson.Gson.fromJson(Gson.java:717) ~[gson-2.2.4.jar:na]
disconf_1  | 	at com.github.knightliao.apollo.utils.data.GsonUtils.parse2Map(GsonUtils.java:44) ~[apollo-1.0.14.jar:na]
disconf_1  | 	at com.baidu.disconf.web.service.config.service.impl.ConfigMgrImpl.compareConfig(ConfigMgrImpl.java:306) ~[classes/:na]
disconf_1  | 	at com.baidu.disconf.web.service.config.service.impl.ConfigMgrImpl.getZkData(ConfigMgrImpl.java:215) ~[classes/:na]
disconf_1  | 	at com.baidu.disconf.web.service.config.service.impl.ConfigMgrImpl.convert(ConfigMgrImpl.java:280) ~[classes/:na]
disconf_1  | 	at com.baidu.disconf.web.service.config.service.impl.ConfigMgrImpl.access$000(ConfigMgrImpl.java:58) ~[classes/:na]
disconf_1  | 	at com.baidu.disconf.web.service.config.service.impl.ConfigMgrImpl$1.transfer(ConfigMgrImpl.java:188) ~[classes/:na]
disconf_1  | 	at com.baidu.disconf.web.service.config.service.impl.ConfigMgrImpl$1.transfer(ConfigMgrImpl.java:176) ~[classes/:na]
disconf_1  | 	at com.baidu.dsp.common.utils.ServiceUtil.getResult(ServiceUtil.java:35) ~[classes/:na]
disconf_1  | 	at com.baidu.disconf.web.service.config.service.impl.ConfigMgrImpl.getConfigList(ConfigMgrImpl.java:176) ~[classes/:na]
disconf_1  | 	at com.baidu.disconf.web.service.config.service.impl.ConfigMgrImpl$$FastClassBySpringCGLIB$$7099537e.invoke(<generated>) ~[spring-core-4.1.7.RELEASE.jar:na]
```

查看zk部署情况是可以看到信息的。

**Comment by ewnit** [comment]
个人排查好像是因为KV值未注入成功转换空类型报错，调试的时候发现当配置文件无后缀的时候直接返回dataMap为null，这算bug么？@knightliao

```
public class DisconfAnyFileProcessorImpl implements DisconfFileTypeProcessor {
    public DisconfAnyFileProcessorImpl() {
    }

    public Map<String, Object> getKvMap(String fileName) throws Exception {
        return null;
    }
}
```

**Comment by knightliao** [comment]
我调试了一下，没有出现这个问题啊
