### ISSUE TITLE
部署server，报连接zookeeper警告，使用的是zk伪集群

### ISSUE THREAD

**Issue by zengcb** [knightliao/disconf#272]
2017-03-02 14:32:35,434 [localhost-startStop-1] WARN  com.baidu.disconf.core.common.zookeeper.inner.ResilientActiveKeyValueStore - exists connect lost... will retry 0	org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /disconf
 2017-03-02 14:32:35,434 [localhost-startStop-1] WARN  com.baidu.disconf.core.common.zookeeper.inner.ResilientActiveKeyValueStore - sleep 2
 2017-03-02 14:32:57,046 [localhost-startStop-1] WARN  com.baidu.disconf.core.common.zookeeper.inner.ResilientActiveKeyValueStore - exists connect lost... will retry 1	org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /disconf
 2017-03-02 14:32:57,046 [localhost-startStop-1] WARN  com.baidu.disconf.core.common.zookeeper.inner.ResilientActiveKeyValueStore - sleep 4
 2017-03-02 14:33:19,004 [localhost-startStop-1] WARN  com.baidu.disconf.core.common.zookeeper.inner.ResilientActiveKeyValueStore - exists connect lost... will retry 2	org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /disconf
 2017-03-02 14:33:19,004 [localhost-startStop-1] WARN  com.baidu.disconf.core.common.zookeeper.inner.ResilientActiveKeyValueStore - sleep 6
 2017-03-02 14:33:20,993 [localhost-startStop-1-EventThread] INFO  com.baidu.disconf.core.common.zookeeper.inner.ConnectionWatcher - zk SyncConnected

**Comment by zengcb** [comment]
而且客户端连接zk集群也包同样的错误，是zk集群配置的问题还是其他问题

**Comment by 734839030** [comment]
me too

**Comment by llyeean** [comment]
2017-08-14 16:49:14,623 [localhost-startStop-1] WARN  com.baidu.disconf.core.common.zookeeper.inner.ResilientActiveKeyValueStore - createEphemeralNode connect lost... will retry 0	org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /disconf/sys_disconf_1_0_0_0_rd/file/idc/biz.properties/sys-PC_0_f1f9ccc3-610e-4a20-ae63-3b3f81934fb7
2017-08-14 16:49:14,623 [localhost-startStop-1] WARN  com.baidu.disconf.core.common.zookeeper.inner.ResilientActiveKeyValueStore - sleep 2
2017-08-14 16:49:16,628 [localhost-startStop-1] WARN  com.baidu.disconf.core.common.zookeeper.inner.ResilientActiveKeyValueStore - createEphemeralNode connect lost... will retry 1	org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /disconf/sys_disconf_1_0_0_0_rd/file/idc/biz.properties/sys-PC_0_f1f9ccc3-610e-4a20-ae63-3b3f81934fb7
2017-08-14 16:49:16,628 [localhost-startStop-1] WARN  com.baidu.disconf.core.common.zookeeper.inner.ResilientActiveKeyValueStore - sleep 4
2017-08-14 16:49:20,633 [localhost-startStop-1] WARN  com.baidu.disconf.core.common.zookeeper.inner.ResilientActiveKeyValueStore - createEphemeralNode connect lost... will retry 2	org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /disconf/sys_disconf_1_0_0_0_rd/file/idc/biz.properties/sys-PC_0_f1f9ccc3-610e-4a20-ae63-3b3f81934fb7
2017-08-14 16:49:20,633 [localhost-startStop-1] WARN  com.baidu.disconf.core.common.zookeeper.inner.ResilientActiveKeyValueStore - sleep 6
2017-08-14 16:49:26,638 [localhost-startStop-1] WARN  com.baidu.disconf.core.common.zookeeper.inner.ResilientActiveKeyValueStore - createEphemeralNode connect lost... will retry 3	org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /disconf/sys_disconf_1_0_0_0_rd/file/idc/biz.properties/sys-PC_0_f1f9ccc3-610e-4a20-ae63-3b3f81934fb7
2017-08-14 16:49:26,638 [localhost-startStop-1] ERROR com.baidu.disconf.client.watch.impl.WatchMgrImpl - cannot create: /disconf/sys_disconf_1_0_0_0_rd/file/idc/biz.properties/sys-PC_0_f1f9ccc3-610e-4a20-ae63-3b3f81934fb7	org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /disconf/sys_disconf_1_0_0_0_rd/file/idc/biz.properties/sys-PC_0_f1f9ccc3-610e-4a20-ae63-3b3f81934fb7
2017-08-14 16:49:26,645 [localhost-startStop-1] ERROR com.baidu.disconf.client.watch.inner.NodeWatcher - cannot monitor /disconf/sys_disconf_1_0_0_0_rd/file/idc/biz.properties
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /disconf/sys_disconf_1_0_0_0_rd/file/idc/biz.properties
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:111) ~[zookeeper-3.4.10.jar:3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[zookeeper-3.4.10.jar:3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f]
	at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1212) ~[zookeeper-3.4.10.jar:3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f]
	at com.baidu.disconf.core.common.zookeeper.inner.ResilientActiveKeyValueStore.read(ResilientActiveKeyValueStore.java:209) ~[disconf-core-2.6.36.jar:na]
	at com.baidu.disconf.core.common.zookeeper.ZookeeperMgr.read(ZookeeperMgr.java:219) ~[disconf-core-2.6.36.jar:na]
	at com.baidu.disconf.client.watch.inner.NodeWatcher.monitorMaster(NodeWatcher.java:59) ~[disconf-client-2.6.36.jar:na]
	at com.baidu.disconf.client.watch.impl.WatchMgrImpl.watchPath(WatchMgrImpl.java:130) [disconf-client-2.6.36.jar:na]
	at com.baidu.disconf.client.core.processor.impl.DisconfFileCoreProcessorImpl.updateOneConfFile(DisconfFileCoreProcessorImpl.java:146) [disconf-client-2.6.36.jar:na]
	at com.baidu.disconf.client.core.processor.impl.DisconfFileCoreProcessorImpl.processOneItem(DisconfFileCoreProcessorImpl.java:78) [disconf-client-2.6.36.jar:na]
	at com.baidu.disconf.client.core.impl.DisconfCoreMgrImpl.processFile(DisconfCoreMgrImpl.java:82) [disconf-client-2.6.36.jar:na]
	at com.baidu.disconf.client.DisconfMgr.reloadableScan(DisconfMgr.java:190) [disconf-client-2.6.36.jar:na]
	at com.baidu.disconf.client.addons.properties.ReloadablePropertiesFactoryBean.setLocations(ReloadablePropertiesFactoryBean.java:66) [disconf-client-2.6.36.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_75]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_75]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
	at org.springframework.beans.BeanWrapperImpl.setPropertyValue(BeanWrapperImpl.java:1158) [spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.beans.BeanWrapperImpl.setPropertyValue(BeanWrapperImpl.java:923) [spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:95) [spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:75) [spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1504) [spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1216) [spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538) [spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) [spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302) [spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:229) [spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298) [spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193) [spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328) [spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108) [spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveManagedList(BeanDefinitionValueResolver.java:359) [spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:157) [spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1471) [spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1216) [spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538) [spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) [spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302) [spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:229) [spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298) [spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:198) [spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:150) [spring-context-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:606) [spring-context-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:462) [spring-context-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403) [spring-web-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306) [spring-web-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106) [spring-web-4.1.1.RELEASE.jar:4.1.1.RELEASE]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4994) [catalina.jar:7.0.57]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5492) [catalina.jar:7.0.57]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:7.0.57]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575) [catalina.jar:7.0.57]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565) [catalina.jar:7.0.57]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
2017-08-14 16:49:26,651 [localhost-startStop-1] DEBUG com.baidu.disconf.client.watch.inner.NodeWatcher - monitor path: (/disconf/sys_disconf_1_0_0_0_rd/file/idc/biz.properties,idc/biz.properties,配置文件) has been added!
2017-08-14 16:49:26,651 [localhost-startStop-1] DEBUG com.baidu.disconf.client.core.processor.impl.DisconfFileCoreProcessorImpl - watch ok.
2017-08-14 16:49:26,651 [localhost-startStop-1] DEBUG com.baidu.disconf.client.DisconfMgr - disconf reloadable file: idc/biz.properties
2017-08-14 16:49:26,654 [localhost-startStop-1] INFO  com.baidu.disconf.client.addons.properties.ReloadablePropertiesFactoryBean - Loading properties file from class path resource [idc/biz.properties]
2017-08-14 16:49:26,656 [localhost-startStop-1] DEBUG c.baidu.disconf.client.addons.properties.ReloadingPropertyPlaceholderConfigurer - add property listener: {autoUserName=sys12345, autoEmail=sys@sys.com, autoPassword=sys}
2017-08-14 16:49:26,990 [localhost-startStop-1] INFO  com.baidu.disconf.client.DisconfMgr - ******************************* DISCONF START SECOND SCAN *******************************

**Comment by llyeean** [comment]
咱俩的错误应该是一样的，不知道怎么解决啊！！！发愁啊

**Comment by xiehuttai** [comment]
什么原因？有解决么
