### ISSUE TITLE
求救！！！启动后台没把配置文件加载出来，不能在界面上查看或修改

### ISSUE THREAD

**Issue by navyzhang** [knightliao/disconf#358]
启动时候报的错是：
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 298
	at com.google.gson.Gson.fromJson(Gson.java:815) ~[gson-2.2.4.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:768) ~[gson-2.2.4.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:717) ~[gson-2.2.4.jar:na]
	at com.github.knightliao.apollo.utils.data.GsonUtils.parse2Map(GsonUtils.java:44) ~[apollo-1.0.14.jar:na]
	at com.baidu.disconf.web.service.config.service.impl.ConfigMgrImpl.compareConfig(ConfigMgrImpl.java:415) ~[classes/:na]
	at com.baidu.disconf.web.service.config.service.impl.ConfigMgrImpl.getZkData(ConfigMgrImpl.java:516) ~[classes/:na]
	at com.baidu.disconf.web.service.config.service.impl.ConfigMgrImpl.convert(ConfigMgrImpl.java:496) ~[classes/:na]
	at com.baidu.disconf.web.service.config.service.impl.ConfigMgrImpl.access$000(ConfigMgrImpl.java:56) ~[classes/:na]
	at com.baidu.disconf.web.service.config.service.impl.ConfigMgrImpl$1.transfer(ConfigMgrImpl.java:187) ~[classes/:na]
	at com.baidu.disconf.web.service.config.service.impl.ConfigMgrImpl$1.transfer(ConfigMgrImpl.java:175) ~[classes/:na]
	at com.baidu.dsp.common.utils.ServiceUtil.getResult(ServiceUtil.java:35) ~[classes/:na]
	at com.baidu.disconf.web.service.config.service.impl.ConfigMgrImpl.getConfigList(ConfigMgrImpl.java:175) ~[classes/:na]
	at com.baidu.disconf.web.web.config.controller.ConfigReadController.getConfigList(ConfigReadController.java:90) ~[classes/:na]

**Comment by sichengLv** [comment]
应该是zk出错了。。。

**Comment by navyzhang** [comment]
是一个同事在配置类的一个配置属性用Map类型，哎，
