### ISSUE TITLE
新增配置项，值可以为空格，修改该配置项，就算改为有效字符，都会提示“服务器内部错误”

### ISSUE THREAD

**Issue by huapuyu** [knightliao/disconf#77]
新增配置项，配置值设为空格，修改该配置项，配置值就算改为有效字符，都会提示“服务器内部错误”
后台日志为：
17:59:27.676 [http-bio-8080-exec-2] WARN  c.b.d.c.handler.MyExceptionHandler - details: 
java.lang.IllegalArgumentException: original must not be null
        at difflib.DiffUtils.diff(DiffUtils.java:95) ~[diffutils-1.3.0.jar:na]
        at difflib.DiffUtils.diff(DiffUtils.java:51) ~[diffutils-1.3.0.jar:na]
        at com.baidu.disconf.web.common.comparator.StringComparator.getDeltas(StringComparator.java:32) ~[classes/:na]
        at com.baidu.disconf.web.common.comparator.CommonComparator.getChunksByType(CommonComparator.java:31) ~[classes/:na]
        at com.baidu.disconf.web.common.comparator.CommonComparator.getChangesFromOriginal(CommonComparator.java:16) ~[classes/:na]
        at com.baidu.disconf.web.utils.DiffUtils.getDiff(DiffUtils.java:55) ~[classes/:na]
        at com.baidu.disconf.web.service.config.service.impl.ConfigMgrImpl.updateItemValue(ConfigMgrImpl.java:428) ~[classes/:na]
        at com.baidu.disconf.web.service.config.service.impl.ConfigMgrImpl$$FastClassBySpringCGLIB$$7099537e.invoke(<generated>) ~[spring-core-4.1.7.RELEASE.jar:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281) ~[spring-tx-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at com.baidu.disconf.web.service.config.service.impl.ConfigMgrImpl$$EnhancerBySpringCGLIB$$11c0729a.updateItemValue(<generated>) ~[spring-core-4.1.7.RELEASE.jar:na]
        at com.baidu.disconf.web.web.config.controller.ConfigUpdateController.updateItem(ConfigUpdateController.java:66) ~[classes/:na]
        at com.baidu.disconf.web.web.config.controller.ConfigUpdateController$$FastClassBySpringCGLIB$$d464ad9d.invoke(<generated>) ~[spring-core-4.1.7.RELEASE.jar:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at com.baidu.disconf.web.service.roleres.service.RoleResourceAspect.decideAccess(RoleResourceAspect.java:109) ~[classes/:na]
        at sun.reflect.GeneratedMethodAccessor105.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav

**Comment by 54ebb** [comment]
新建节点a，值为\b：结果mysql写进去了，zk上没有

**Comment by huapuyu** [comment]
好的，谢谢，下一版本会修复吗？

**Comment by knightliao** [comment]
关注，我复现下
