### ISSUE TITLE
java.lang.Exception: status is not ok(From DisconfItemCoreProcessorImpl)

### ISSUE THREAD

**Issue by bwzhang2011** [knightliao/disconf#90]
@knightliao, 使用2.6.32发现这样的问题
ERROR com.baidu.disconf.client.core.processor.impl.DisconfItemCoreProcessorImpl. main cannot use remote configuration: basicrouterlist
java.lang.Exception: status is not ok.
	at com.baidu.disconf.client.fetcher.impl.FetcherMgrImpl.getValueFromServer(FetcherMgrImpl.java:80) ~[classes/:?]
	at com.baidu.disconf.client.core.processor.impl.DisconfItemCoreProcessorImpl.updateOneConfItem(DisconfItemCoreProcessorImpl.java:112) ~[classes/:?]
	at com.baidu.disconf.client.core.processor.impl.DisconfItemCoreProcessorImpl.processOneItem(DisconfItemCoreProcessorImpl.java:69) ~[classes/:?]
	at com.baidu.disconf.client.core.processor.impl.DisconfItemCoreProcessorImpl.processAllItems(DisconfItemCoreProcessorImpl.java:58) ~[classes/:?]
	at com.baidu.disconf.client.core.impl.DisconfCoreMgrImpl.process(DisconfCoreMgrImpl.java:69) ~[classes/:?]
	at com.baidu.disconf.client.DisconfMgr.firstScan(DisconfMgr.java:97) ~[classes/:?]
	at com.baidu.disconf.client.DisconfMgrBean.postProcessBeanDefinitionRegistry(DisconfMgrBean.java:75) ~[classes/:?]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]

上述错误导致：
ERROR com.baidu.disconf.client.watch.impl.WatchMgrImpl. main cannot create: /disconf/test/routerproxy_1_0_0_0_rd/item/basicrouterlist/DELL-PC_0_53059361-75a4-4379-9a1a-c316c35bf332	java.lang.NullPointerException

说明：
 basicrouterlist这个选项实际上已经在加载的文件中了（本地仓库还是远端都已经有该记录了），但仍然提示报错。请问是否有遇到这样的问题

**Comment by bwzhang2011** [comment]
@knightliao, 看错了内部的配置是
@DisconfItem(key = XXX） 需要单独增加配置项的条目支持，增加后恢复正常。
